name: Karma Tests

on:
  workflow_call:

jobs:
  karma-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'
    - name: Install w/ legacy-peer-deps
      run: npm ci --legacy-peer-deps
    - name: Install Puppeteer (headless Chrome)
      run: npm install puppeteer --legacy-peer-deps --save-dev
    - name: Run tests
      run: |
        npm run test:ci > test_output.txt
        TEST_RESULTS=$(cat test_output.txt)
        echo "karma_output<<EOF" >> "$GITHUB_OUTPUT"
        echo "$TEST_RESULTS" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
        echo "{markdown content}" >> $GITHUB_STEP_SUMMARY
    - name: Set Job Summary
      run: |
        echo "### Karma Results  ${{steps.run_tests.outputs.karma_output}}" >> $GITHUB_STEP_SUMMARY
