name: Karma Tests

on:
  workflow_call:

jobs:
  karma-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'
    - name: Install w/ legacy-peer-deps
      run: npm ci --legacy-peer-deps
    - name: Install Puppeteer (headless Chrome)
      run: npm install puppeteer --legacy-peer-deps --save-dev
    - name: Run tests
      id: karma-test
      run: |
        TEST_OUTPUT=$(npm run test:ci || true)
        echo "test_results<<EOF" >> "$GITHUB_OUTPUT"
        echo "$TEST_OUTPUT" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Set Job Summary
      run: |
        RESULTS="${{ steps.karma-test.outputs.test_results }}"
        echo "### Karma Test Results" >> "$GITHUB_STEP_SUMMARY"
        echo '```markdown' >> "$GITHUB_STEP_SUMMARY"
        echo "$RESULTS" >> "$GITHUB_STEP_SUMMARY"
        echo '```' >> "$GITHUB_STEP_SUMMARY"
      shell: bash
